spring:
  datasource:
    url: jdbc:h2:mem:bankdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: create-drop

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

server:
  port: 8080

logging:
  level:
    root: INFO
    com.bank: DEBUG
    org.springframework.security: TRACE
    org.hibernate.SQL: DEBUG

management:

  endpoints:

    web:

      exposure:

        include: health,info,metrics

  endpoint:

    health:

      show-details: always

springdoc:

  api-docs:

    path: /api-docs

  swagger-ui:

    path: /swagger-ui.html

jwt:

  secret: 1234567890123456789012345678901234567890123456789012345678901234

  expiration: 3600000